name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    ci-cd:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: store_manager
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

        steps:
            # - name: Cloner dépôt
              # uses: actions/checkout@v3
  
            - name: Cloner dépôt (deep checkout)
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
                submodules: recursive

            - name: Configurer Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Installer les dépendances
              run: |
                  pip install pylint pytest sqlalchemy
                  # Retirez 'pip install -e .' si vous n'avez pas de setup.py

            - name: Linter tous les fichiers Python
              run: |
                  find . -name "*.py" -not -path "./__pycache__/*" -not -path "./.venv/*" | xargs pylint --exit-zero || true

            - name: Lancer les tests (skippables)
              run: |
                  PYTHONPATH=$PYTHONPATH:./src pytest -v

            - name: Préparer Docker pour le build
              uses: docker/setup-buildx-action@v3

            - name: Connexion à Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Vérifier la structure des fichiers
              run: |
                echo "Structure complète :"
                ls -R
                echo "Contenu de backend/docker :"
                ls -l backend/docker/

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  file: ./docker/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
